### ISSUE TITLE
Asset Service Todo

### ISSUE THREAD

**Issue by moorara** [moorara/microservices-demo#92]
- [x] Use **CockroachDB**
  - [x] API paradigm: messaging using **NATS**
  - [x] Component tests
  - [x] GraphQL gateway integration
  - [x] Update system diagrams

**Comment by moorara** [comment]
Addressed in #93 #94 #98 #95 #101
